name: mlit_sdk
description: A Fluter SDK for accessing Japan's Ministry of Land, Infrastructure, Transport and Tourism (MLIT) Real Estate Information Library APIs
version: 1.1.0
repository: https://github.com/erknvl/mlit_sdk

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  dartz: 0.10.1
  dio: ^5.8.0+1
  equatable: 2.0.7
  freezed_annotation: 3.0.0
  json_annotation: 4.9.0
  lint: ^2.8.0
  lints: 6.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.4.15
  freezed: 3.0.6
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  test: ^1.26.2

topics:
  - mlit
  - real-estate
  - japan
  - geo

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
